### ISSUE TITLE
Function highlighting Doesn't Support Unicode Function Names

### ISSUE THREAD

**Issue by jeremiahpslewis** [tpoisot/language-julia#1]
The function highlighting doesn't support Unicode function names. A potential broad-based fix could be to paste in a list of all possible unicode characters [here](http://stackoverflow.com/questions/6381752/validating-users-utf-8-name-in-javascript) ... but also not the prettiest solution.

![screen shot 2015-03-24 at 18 08 43](https://cloud.githubusercontent.com/assets/4462211/6820803/934c905e-d2d2-11e4-9e45-2d49b896972b.png)
![screen shot 2015-03-24 at 18 08 17](https://cloud.githubusercontent.com/assets/4462211/6820805/952d4aee-d2d2-11e4-93bd-a1f0ede565bc.png)

**Comment by tpoisot** [comment]
Not pretty, but it might work. I'll think it over, but if you want to go ahead and try, then do.

**Comment by tpoisot** [comment]
I've added a more general solution in `0.8.0`.
