### ISSUE TITLE
"$ will result in a wrong coloring 

### ISSUE THREAD

**Issue by Gnimuc** [tpoisot/language-julia#8]
if we write

```
println("$(foo)")
println("those lines below the first line will be colored as strings")
```

everything seems like to be ok if we add a space between " and $ in the first line `println(" $(foo)")`

**Comment by merqurio** [comment]
I found the same problem when I was checking Gadfly at [this line](https://github.com/dcjones/Gadfly.jl/blob/master/src/Gadfly.jl#L282) in Atom, I guess it's `$` faults.
:grin: 

![Example of the error](http://lh3.googleusercontent.com/0O5wjQQyOH0i1agxKwX48gZtaVtJD5ohFbZCDR8hAjo6hnB5Umo1yPVGUlST8AQkl9uNRCVXrntMMvVVq--sMBcslxrm=s1600)

**Comment by Gnimuc** [comment]
got fixed. many thanks :+1:
